name: CI
on:
  pull_request:
  push:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.*

      - name: Configure PATH for tools
        run: echo "/home/runner/.dotnet/tools" >> $GITHUB_PATH

      - name: Run tests and generate coverage
        run: |
          dotnet test -c Release --collect:"XPlat Code Coverage"

      - name: Convert coverage to LCOV
        run: |
          reportgenerator -reports:"**/TestResults/**/*.cobertura.xml" -targetdir:"coverage" -reporttypes:lcov
        env:
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
          DOTNET_CLI_TELEMETRY_OPTOUT: true

      - name: Report coverage
        continue-on-error: true
        uses: coverallsapp/github-action@v2.3.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage/lcov.info